---
# This playbook tests the script module on Windows hosts
- hosts: all 
  gather_facts: false
  tasks:
    - name: Creando el directorio C:\TEMP
      win_file:
        path: C:\Temp
        state: directory  
  
  
  
    - name: Copiando el fichero usurios.txt
      win_copy:
       src: crearusuarios/usuarios.txt
       dest: C:\Temp\


    - name: Ejecutando Script para crear usuarios desde fichero usuarios.txt
      script: crearusuarios/crearusuarios.ps1


    - name: Eliminando el fichero usuarios.txt.
      win_file:
       path: C:\Temp\usuarios.txt
       state: absent



    - name: Eliminado el directorio C:\TEMP
      win_file:
        path: C:\Temp
        state: absent
